server:
  port: 9198
  servlet:
    context-path: /insurence-service

spring:
  application:
    name: INSURENCE-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/insurence_db?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: rahal
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://127.0.0.1:8761/eureka/}

  instance:
    hostname: ${DOMAIN:localhost}